spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG
  r2dbc:
    url: r2dbc:mysql://localhost:3306/todo_db
    username: root
    password: root
  graphql:
    graphiql:
      enabled: true
  webflux:
    base-path: /api

logging:
  level:
    org.springframework: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: DEBUG