spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  logging:
    level:
      org.springframework: DEBUG
      org.springframework.r2dbc: DEBUG
      org.springframework.graphql: DEBUG
      org.springframework.web: DEBUG
      org.springframework.boot.autoconfigure: DEBUG
      io.r2dbc.mysql: DEBUG  # Add this line for R2DBC MySQL logging
      org.springframework.data.r2dbc: DEBUG  # Add this line for Spring Data R2DBC logging
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    path: /graphql
    cors:
      allowed-origins: http://localhost:3000
  r2dbc:
    url: r2dbc:mysql://localhost:3306/todo_db
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/todo_db
    user: root
    password: root
    locations: classpath:db/migration
    baselineOnMigrate: true  # Add this line
    baselineVersion: 0  # Add this line

logging:
  level:
    org.springframework: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    io.r2dbc.mysql: DEBUG  # Add this line for R2DBC MySQL logging
    org.springframework.data.r2dbc: DEBUG  # Add this line for Spring Data R2DBC logging
    io.r2dbc.mysql.QUERY: DEBUG  # Add this line to log SQL queries
    io.r2dbc.mysql.PARAM: DEBUG  # Add this line to log SQL parameters

notion:
  api:
    key: your_notion_api_key_here
    version: 2022-06-28