spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true